sed "s/xxxxx/stdout_C2_T3_data_m_jpg/" make3Dgraph_BigChar.plt | gnuplot
sed "s/xxxxx/stdout_C2_T4_data_m_jpg/" make3Dgraph_BigChar.plt | gnuplot
sed "s/xxxxx/stdout_C2_T5_data_m_jpg/" make3Dgraph_BigChar.plt | gnuplot
sed "s/xxxxx/stdout_C2_T6_data_m_jpg/" make3Dgraph_BigChar.plt | gnuplot
sed "s/xxxxx/stdout_C3_T3_data_m_jpg/" make3Dgraph_BigChar.plt | gnuplot
sed "s/xxxxx/stdout_C3_T4_data_m_jpg/" make3Dgraph_BigChar.plt | gnuplot
sed "s/xxxxx/stdout_C4_T3_data_m_jpg/" make3Dgraph_BigChar.plt | gnuplot
sed "s/xxxxx/stdout_C4_T4_data_m_jpg/" make3Dgraph_BigChar.plt | gnuplot
sed "s/xxxxx/stdout_C4_T5_data_m_jpg/" make3Dgraph_BigChar.plt | gnuplot
