python.exe modify_data.py stdout_C2_T3_data.txt stdout_C2_T3_data_m.txt
python.exe modify_data.py stdout_C2_T4_data.txt stdout_C2_T4_data_m.txt
python.exe modify_data.py stdout_C2_T5_data.txt stdout_C2_T5_data_m.txt
python.exe modify_data.py stdout_C2_T6_data.txt stdout_C2_T6_data_m.txt
python.exe modify_data.py stdout_C3_T3_data.txt stdout_C3_T3_data_m.txt
python.exe modify_data.py stdout_C3_T4_data.txt stdout_C3_T4_data_m.txt
python.exe modify_data.py stdout_C4_T3_data.txt stdout_C4_T3_data_m.txt
python.exe modify_data.py stdout_C4_T4_data.txt stdout_C4_T4_data_m.txt
python.exe modify_data.py stdout_C4_T5_data.txt stdout_C4_T5_data_m.txt
