python.exe calc_time.py stdout_C2_T3.txt > time.txt
python.exe calc_time.py stdout_C2_T4.txt >> time.txt
python.exe calc_time.py stdout_C2_T5.txt >> time.txt
python.exe calc_time.py stdout_C2_T6.txt >> time.txt
python.exe calc_time.py stdout_C3_T3.txt >> time.txt
python.exe calc_time.py stdout_C3_T4.txt >> time.txt
python.exe calc_time.py stdout_C4_T3.txt >> time.txt
python.exe calc_time.py stdout_C4_T4.txt >> time.txt
python.exe calc_time.py stdout_C4_T5.txt >> time.txt
